### ISSUE TITLE
iPhone Safari not rendering `test` branch properly

### ISSUE THREAD

**Issue by yaboi** [mysticetus-inc/dotcom#26]
Reported by @PDonlan:

<img src="https://user-images.githubusercontent.com/1933226/53656721-018e8380-3c09-11e9-936a-ed397cb1a03b.png" width="400px" />

**TODO:**
- Tyler to test on ipod & iphone to try and recreate

**Comment by PDonlan** [comment]
fixed, this is due to content blocking 'other' feature in firefox focus. resolved
